apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-app
  namespaceSelector:
    matchNames:
    - devops
  endpoints:
  - port: spring-service
    path: /student/actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
