apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/devopsdb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==        # root
  SPRING_DATASOURCE_PASSWORD: cm9vdDEyMw==    # root123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo "Waiting for MySQL..."; sleep 2; done; echo "MySQL is ready!"']
      containers:
      - name: spring-app
        image: azizlaribi/monprojet:latest
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: spring-config
        - secretRef:
            name: spring-secret
        readinessProbe:
          httpGet:
            path: /student/Depatment/getAllDepartment
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /student/Depatment/getAllDepartment
            port: 8089
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
  type: NodePort
