global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Spring Boot Application
  - job_name: 'student-management-app'
    metrics_path: '/student/actuator/prometheus'
    static_configs:
      - targets: ['192.168.49.2:30080']
        labels:
          application: 'student-management'
          service: 'spring-boot'

  # 2. Jenkins
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          service: 'jenkins'
          application: 'student-management'

  # 3. Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'host-metrics'
          job: 'node-exporter'

  # 4. Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']