apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  application.properties: |
    # Server
    server.servlet.context-path=/student
    server.port=8089
    
    # Database
    spring.datasource.url=jdbc:mysql://mysql-service:3306/studentdb
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
    # JPA
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.show-sql=true
    
    # Actuator - Prometheus Metrics (CRITICAL)
    management.endpoints.web.exposure.include=health,info,prometheus,metrics
    management.endpoint.health.show-details=always
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.tags.application=student-management
    management.metrics.tags.environment=devops
    
    # Enable actuator
    management.endpoints.enabled-by-default=true
    
    # Logging
    logging.level.org.springframework.web=INFO
    logging.level.tn.esprit=DEBUG
    logging.level.org.springframework.boot.actuate=DEBUG
